### PR TITLE
make sure that visualize_urdf.py has runable arguments for robot_name and model_name

### PR DESCRIPTION
**Pull request by saraybakker1**
arguments were still set to old version

### CODE REVIEW

**Comment by saraybakker1** [comment]
@maxspahn, one issue. the local_urdf.py doesn't run for me, "urdf not found error', also not for the panda example

**Comment by maxspahn** [comment]
I think these changes have identically fixed in 474dccb, right?

**Comment by maxspahn** [comment]
Ah, the default arguments were actually wrong.
Such as the model path.
Both fixed in 1fe5fa6d990bb4dc326ce1a6267f7cee1e6b738b

**Comment by maxspahn** [comment]
Closing because addressed in mentioned PR's.

**Pull request closed without merging**
